container_digests:
  - wave.seqera.io/wt/d614111936ef/nextflow/bash:latest
launched_at: '2026-06-05T09:42:48.215Z'
launched_by: CiQwOGE4Njg0Yi1kYjg4LTRiNzMtOTBhOS0zY2QxNjYxZjU0NjYSBWxvY2Fs
output_dir: null
outputs: []
params_hash: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
pipeline:
  repo: https://github.com/nextflow-io/hello
run_id: a475ca8b-a42c-4eb6-823b-1d977f5e199a
